### ISSUE TITLE
What does your mac dock look like?

### ISSUE THREAD

**Issue by robbbz** [wbinnssmith/ama#11]

**Comment by wbinnssmith** [comment]
Interesting assumption that I use a Mac :stuck_out_tongue: Anyway, you're right, generally speaking. I use a Mac at work but dual boot Windows 10 and Ubuntu at home. Here's my dock:

<img width="86" alt="screenshot 2015-08-25 21 21 18" src="https://cloud.githubusercontent.com/assets/755844/9485554/f976de96-4b6f-11e5-8ce4-22bcc4c8a9c7.png">

It's usually mostly this or some variation, but I tend to keep it as minimal as possible. Chrome stable for what our users are likely to see (I'll of course spin up other browsers manually and through automated tests) and Canary to play with the latest goodies.

I have HipChat on 24/7 for obvious reasons, but was a HipChat lover long before I started at Atlassian. Too bad the rest of life can't be expressed with emoticons.

I've got neovim running in iTerm within a split shared with zsh for scratch, and more shell instances in tabs tailing the various pieces of Bitbucket. I'll also spin up Activity Monitor or htop when the fans kick in or I notice battery drop quickly. Oh, and I also can't live without TweetBot in the menubar.

**Comment by wbinnssmith** [comment]
Oh, and the Hangouts chrome app. It's all right, certainly better than living in Gmail, but dedicated Chrome apps on OS X still have a long ways to go compared to their Windows and Linux counterparts. Also on Hangouts 24/7, especially on my phone.
